### ISSUE TITLE
Random "WSMAN ERROR CODE: 2150858843" when using test-kitchen on ec2 boxes

### ISSUE THREAD

**Issue by kamaradclimber** [WinRb/WinRM#253]
Hello,

when asking test-kitchen to use ec2 instances (for windows), this gem crashes with the reporting the following error:
```
E, [2017-03-01T09:40:53.367865 #39922] ERROR -- default-chef-future-windows-2012r2: Class: WinRM::WinRMWSManFault
E, [2017-03-01T09:40:53.367923 #39922] ERROR -- default-chef-future-windows-2012r2: Message: [WSMAN ERROR CODE: 2150858843]: <f:WSManFault Code='2150858843' Machine='ec2-52-36-179-208.us-west-2.compute.amazonaws.com' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The request for the Windows Remote Shell with ShellId 128FBD1C-CDFC-44DA-832F-EFD5D5CCB4FD failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. </f:Message></f:WSManFault>
E, [2017-03-01T09:40:53.367947 #39922] ERROR -- default-chef-future-windows-2012r2: ----------------------
E, [2017-03-01T09:40:53.367970 #39922] ERROR -- default-chef-future-windows-2012r2: ------Backtrace-------
E, [2017-03-01T09:40:53.367991 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/http/response_handler.rb:69:in `raise_if_wsman_fault'
E, [2017-03-01T09:40:53.368013 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/http/response_handler.rb:52:in `raise_if_error'
E, [2017-03-01T09:40:53.368036 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/http/response_handler.rb:36:in `parse_to_xml'
E, [2017-03-01T09:40:53.368078 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/http/transport.rb:186:in `send_request'
E, [2017-03-01T09:40:53.368102 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/http/transport.rb:181:in `send_request'
E, [2017-03-01T09:40:53.368128 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/shells/base.rb:151:in `cleanup_command'
E, [2017-03-01T09:40:53.368153 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/shells/base.rb:133:in `ensure in with_command_shell'
E, [2017-03-01T09:40:53.368174 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/shells/base.rb:133:in `with_command_shell'
E, [2017-03-01T09:40:53.368195 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-2.1.2/lib/winrm/shells/base.rb:80:in `run'
E, [2017-03-01T09:40:53.368216 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/winrm-elevated-1.1.0/lib/winrm/shells/elevated.rb:60:in `run'
E, [2017-03-01T09:40:53.368236 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/transport/winrm.rb:218:in `execute_with_exit_code'
E, [2017-03-01T09:40:53.368266 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/transport/winrm.rb:100:in `execute'
E, [2017-03-01T09:40:53.368288 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/transport/winrm.rb:140:in `wait_until_ready'
E, [2017-03-01T09:40:53.368309 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/bundler/gems/kitchen-ec2-ee507fe3a15a/lib/kitchen/driver/ec2.rb:224:in `create'
E, [2017-03-01T09:40:53.368330 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-03-01T09:40:53.368357 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-03-01T09:40:53.368380 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-01T09:40:53.368400 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-01T09:40:53.368420 #39922] ERROR -- default-chef-future-windows-2012r2: /usr/lib64/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2017-03-01T09:40:53.368440 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-01T09:40:53.368460 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-03-01T09:40:53.368480 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-03-01T09:40:53.368500 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-01T09:40:53.368520 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-01T09:40:53.368545 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-01T09:40:53.368569 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-03-01T09:40:53.368590 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-03-01T09:40:53.368617 #39922] ERROR -- default-chef-future-windows-2012r2: /usr/lib64/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2017-03-01T09:40:53.368638 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-03-01T09:40:53.368658 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-01T09:40:53.368679 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-01T09:40:53.368699 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-01T09:40:53.368719 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
E, [2017-03-01T09:40:53.368740 #39922] ERROR -- default-chef-future-windows-2012r2: /home/jenkins/.gem/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

This seems to be random, even though some of our users reported getting rid of it by increasing ec2 instance size (not confirmed).

Here is the output of kitchen diagnose for this suite:
```
---
timestamp: 2017-03-01 09:54:30 UTC
kitchen_version: 1.15.0
instances:
  unregister-chef-future-windows-2012r2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file: {}
    driver:
      associate_public_ip: true
      availability_zone: 
      aws_access_key_id: 
      aws_secret_access_key: 
      aws_session_token: 
      aws_ssh_key_id: g.seux
      block_device_mappings:
      - device_name: "/dev/sda1"
        ebs:
          volume_type: gp2
          delete_on_termination: true
      block_duration_minutes: 
      ebs_optimized: false
      http_proxy: 
      iam_profile_name: test-kitchen
      image_id: ami-c626a0a6
      image_search:
        name: Windows_Server-2012-R2_RTM-English-64Bit-Base-*
      instance_initiated_shutdown_behavior: 
      instance_type: t2.medium
      interface: 
      kitchen_root: "/home/g_seux/cookbooks/consul-criteo"
      log_level: :info
      name: ec2
      private_ip_address: 
      region: us-west-2
      retry_limit: 3
      retryable_sleep: 5
      retryable_tries: 60
      security_group_filter:
        tag: Name
        value: node-security-group
      security_group_ids: 
      shared_credentials_profile: 
      spot_price: 
      subnet_filter:
        tag: Name
        value: chef-testing-closedsource-gw-vpc-subnet
      tags:
        created-by: g.seux
      tenancy: default
      test_base_path: "/home/g_seux/cookbooks/consul-criteo/test/integration"
      user_data: |
        <powershell>
        $logfile=C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log
        # Allow script execution
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
        #PS Remoting and & winrm.cmd basic config
        Enable-PSRemoting -Force -SkipNetworkProfileCheck
        & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $logfile
        #Server settings - support username/password login
        & winrm.cmd set winrm/config/service/auth '@{Basic="true"}' >> $logfile
        & winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        #Firewall Config
        & netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" profile=public protocol=tcp localport=5985 remoteip=localsubnet new remoteip=any  >> $logfile

        </powershell>
      username: 
    provisioner:
      always_update_cookbooks: false
      attributes:
        kitchen_ohai:
          values:
            location:
              datacenter: PAR
        authorization:
          sudo:
            users:
            - centos
        consul_criteo:
          enable_monitoring: false
          purge: true
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options: 
      chef_omnibus_url: http://filer.criteo.preprod/omnibus_install_future.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      install_msi_url: http://filer.criteo.preprod/chef-client-future.msi
      json_attributes: true
      kitchen_root: "/home/g_seux/cookbooks/consul-criteo"
      log_file: 
      log_level: auto
      max_retries: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: 
      policyfile: 
      policyfile_path: 
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: 
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[yum-criteo]
      - recipe[consul-criteo]
      - recipe[consul-criteo::unregister]
      sudo: 
      sudo_command: 
      test_base_path: "/home/g_seux/cookbooks/consul-criteo/test/integration"
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: true
      elevated_password: 
      elevated_username: System
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/home/g_seux/cookbooks/consul-criteo"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: 
      port: 5985
      rdp_port: 3389
      ssh_key: "/home/g_seux/.ssh/id_rsa"
      test_base_path: "/home/g_seux/cookbooks/consul-criteo/test/integration"
      username: administrator
      winrm_transport: :negotiate
    verifier:
      busser_bin: "$env:TEMP\\verifier\\bin\\busser.bat"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/home/g_seux/cookbooks/consul-criteo"
      log_level: :info
      name: busser
      root_path: "$env:TEMP\\verifier"
      ruby_bindir: "$env:systemdrive\\opscode\\chef\\embedded\\bin"
      sudo: 
      sudo_command: 
      suite_name: unregister-chef-future
      test_base_path: "/home/g_seux/cookbooks/consul-criteo/test/integration"
      version: busser
```

Since this happens on create phase (and this happens on various suites in different cookbooks), I think we can be reproduced with test-kitchen on open source cookbooks.

Would you have a hint on how to solve that issue?
