### ISSUE TITLE
2150858843 - The request for the Windows Remote Shell with ShellId 37019EC2-6D37-4211-B2F2-05FD17AAD8AA failed because the shell was not found on the server.

### ISSUE THREAD

**Issue by fourth-barryleonard** [WinRb/WinRM#273]
Hi,

We're using the WinRM gem as part of the ChefDK (we run ChefDK in a docker container - the docker image is `chef/chefdk:2.0.12`) 

We're seeing intermittent issues with test kitchen converges and we're trying to get to the root cause. We're starting with the WinRM gem repo as there are some closed issues recently for the error we're seeing. The error is:

```
[windows2012r2_sql2012_sp2_cu4_serviceaccounts] >>>>>> ------Exception-------
[windows2012r2_sql2012_sp2_cu4_serviceaccounts] >>>>>> Class: Kitchen::ActionFailed
[windows2012r2_sql2012_sp2_cu4_serviceaccounts] >>>>>> Message: 1 actions failed.
[windows2012r2_sql2012_sp2_cu4_serviceaccounts] >>>>>>     Failed to complete #converge action: [[WSMAN ERROR CODE: 2150858843]: <f:WSManFault Code='2150858843' Machine='<redacted IP>' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The request for the Windows Remote Shell with ShellId 37019EC2-6D37-4211-B2F2-05FD17AAD8AA failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. </f:Message></f:WSManFault>] on sqlserver2012-dev-sp2-cu4-sa-windows2012-r2
```

The version of the WinRM gem is 2.2.3 (verified with chef gem list)

The point where this error seems to trigger is when the machine goes down for a reboot. Here's a snippet of our kitchen YAML which shows we're setup to handle that reboot:

```
---
driver:
  name: azurerm

driver_config:
  subscription_id: '<redacted subID>'
  location: 'North Europe'
  machine_size: 'Standard_F2'

transport:
  name: winrm
  elevated: true
  elevated_username: <%= ENV['AZURETESTKITCHENUSERNAME'] %>
  elevated_password:  <%= ENV['AZURETESTKITCHENPASSWORD'] %>
  connection_retries: 600
  connection_retry_sleep: 5

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "debug" %>
  require_chef_omnibus: 12.19.36 # We need this for choco provider returns functionality
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  wait_for_retry: 300
  max_retries: 300
  environments_path: test/integration/environments
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    environment: test_platform

platforms:
  - name: windows2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest

  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest

---
```

Gem list output and ChefDK versions:

```
root@8ea0a43ff1de:/# chef --version
Chef Development Kit Version: 2.0.12
chef-client version: 13.0.118
delivery version: master (651e8c7e37fc80d6e1867a176974bf41fb08aa98)
berks version: 6.1.0
kitchen version: 1.16.0
inspec version: 1.26.0
root@8ea0a43ff1de:/# chef gem list

*** LOCAL GEMS ***

activesupport (4.2.8)
addressable (2.5.1)
app_conf (0.4.2)
appbundler (0.10.0)
artifactory (2.8.1)
ast (2.3.0)
autoparse (0.3.3)
aws-sdk (2.9.26)
aws-sdk-core (2.9.26)
aws-sdk-resources (2.9.26)
aws-sdk-v1 (1.67.0)
aws-sigv4 (1.0.0)
berkshelf (6.1.0)
berkshelf-api-client (3.0.0)
bigdecimal (default: 1.3.0)
binding_of_caller (0.7.2)
blankslate (2.1.2.4)
buff-config (2.0.0)
buff-extensions (2.0.0)
buff-ignore (1.2.0)
buff-ruby_engine (1.0.0)
buff-shell_out (1.1.0)
builder (3.2.3)
bundler (1.14.6)
byebug (9.0.6)
celluloid (0.16.0)
celluloid-io (0.16.2)
CFPropertyList (2.3.5)
chef (13.0.118)
chef-config (13.1.31, 13.0.118)
chef-dk (2.0.12)
chef-provisioning (2.3.2)
chef-provisioning-aws (2.2.0)
chef-provisioning-azure (0.6.0)
chef-provisioning-fog (0.21.0)
chef-sugar (3.4.0)
chef-vault (3.0.3)
chef-zero (13.0.0)
cheffish (13.0.0)
chefspec (7.1.0)
cleanroom (1.0.0)
coderay (1.1.1)
concurrent-ruby (1.0.5)
cookbook-omnifetch (0.6.0)
cookstyle (1.4.0)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
dco (1.0.1)
debug_inspector (0.0.3)
dep-selector-libgecode (1.3.1)
dep_selector (1.0.4)
did_you_mean (1.1.0)
diff-lcs (1.3)
diffy (3.2.0)
docker-api (1.33.4)
erubis (2.7.0)
excon (0.56.0)
extlib (0.9.16)
faraday (0.12.1)
faraday-http-cache (2.0.0)
fauxhai (4.1.0)
ffi (1.9.18)
ffi-rzmq (2.0.5)
ffi-rzmq-core (1.0.6)
ffi-yajl (2.3.0)
fission (0.5.0)
fog (1.40.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (1.3.0)
fog-brightbox (0.11.0)
fog-cloudatcost (0.1.2)
fog-core (1.44.3)
fog-digitalocean (0.3.0)
fog-dnsimple (1.0.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-json (1.0.2)
fog-local (0.3.1)
fog-openstack (0.1.21)
fog-powerdns (0.1.1)
fog-profitbricks (3.0.0)
fog-rackspace (0.1.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-scaleway (0.2.1)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.10.0)
fog-xenserver (0.3.0)
fog-xml (0.1.3)
foodcritic (11.1.0)
formatador (0.2.5)
fuzzyurl (0.9.0)
gherkin (4.1.3)
git (1.3.0)
google-api-client (0.8.7)
googleauth (0.5.1)
gssapi (1.2.0)
guard (2.14.1)
gyoku (1.3.1)
hashie (3.5.5)
highline (1.7.8)
hitimes (1.2.5)
httpclient (2.8.3)
i18n (0.8.4)
inflecto (0.0.2)
inifile (3.0.0)
iniparse (1.4.2)
inspec (1.26.0)
io-console (default: 0.4.6)
ipaddress (0.8.3)
iso8601 (0.9.1)
jmespath (1.3.1)
json (default: 2.0.2, 1.8.6)
jwt (1.5.6)
kitchen-dokken (2.1.6)
kitchen-ec2 (1.3.2)
kitchen-inspec (0.19.0)
kitchen-vagrant (1.1.0)
knife-opc (0.3.2)
knife-push (1.0.2)
knife-spork (1.6.3)
knife-windows (1.9.0)
launchy (2.4.3)
libyajl2 (1.2.0)
listen (3.1.5)
little-plugger (1.1.4)
logging (2.2.2)
lumberjack (1.0.12)
macaddr (1.7.1)
memoist (0.15.0)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitar (0.5.4)
minitest (5.10.2, 5.10.1)
mixlib-archive (0.4.1)
mixlib-authentication (1.4.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-install (2.1.12)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
mixlib-versioning (1.1.0)
molinillo (0.5.7)
multi_json (1.12.1)
multi_test (0.1.2)
multipart-post (2.0.0)
nenv (0.3.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.1.0)
net-ssh-gateway (1.3.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
nio4r (2.1.0)
nokogiri (1.7.2)
nori (2.6.0)
notiffany (0.1.1)
octokit (4.7.0)
ohai (13.1.0)
openssl (default: 2.0.3)
opscode-pushy-client (2.3.0)
os (0.9.6)
paint (1.0.1)
parallel (1.11.2)
parser (2.4.0.0)
parslet (1.5.0)
plist (3.3.0)
polyglot (0.3.5)
power_assert (0.4.1)
powerpack (0.1.1)
proxifier (1.0.3)
pry (0.10.4)
pry-byebug (3.4.2)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.2)
psych (default: 2.2.2)
public_suffix (2.0.5)
rack (2.0.3)
rainbow (2.2.2)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rb-readline (0.5.4)
rbvmomi (1.11.2)
rdoc (5.1.0, default: 5.0.0)
retriable (1.4.1)
retryable (2.0.4)
ridley (5.1.1)
rspec (3.6.0)
rspec-core (3.6.0)
rspec-expectations (3.6.0)
rspec-its (1.2.0)
rspec-mocks (3.6.0)
rspec-support (3.6.0)
rspec_junit_formatter (0.2.3)
rubocop (0.47.1)
ruby-prof (0.16.2)
ruby-progressbar (1.8.1)
ruby-shadow (2.5.0)
ruby_dep (1.5.0)
rubyntlm (0.6.2)
rubyzip (1.2.1)
rufus-lru (1.1.0)
safe_yaml (1.0.4)
sawyer (0.8.1)
semverse (2.0.0)
serverspec (2.39.1)
sfl (2.3)
shellany (0.0.1)
signet (0.7.3)
slop (3.6.0)
solve (3.1.0)
specinfra (2.68.0)
sslshake (1.2.0)
stuartpreston-azure-sdk-for-ruby (0.7.2)
syslog-logger (1.6.8)
systemu (2.6.5)
test-kitchen (1.16.0)
test-unit (3.2.3)
thor (0.19.1)
thread_safe (0.3.6)
timers (4.0.4)
toml (0.1.2)
train (0.24.0)
treetop (1.6.8)
trollop (2.1.2)
tzinfo (1.2.3)
ubuntu_ami (0.4.1)
unicode-display_width (1.2.1)
uuid (2.3.8)
uuidtools (2.1.5)
varia_model (0.6.0)
winrm (2.2.3)
winrm-elevated (1.1.0)
winrm-fs (1.0.1)
wmi-lite (1.0.0)
xml-simple (1.1.5)
xmlrpc (0.2.1)
yajl-ruby (1.3.0)
yard (0.9.9)
```

Does anyone have any ideas on this one/is anyone else seeing this?

Thanks,

Barry
